version: '3'

services:
  mysqldb:
    image: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysqldb:/var/lib/mysql'
    networks:
      - bridge
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
  blog:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    networks:
      - bridge
    volumes:
      - '.:/var/www/html'
    depends_on:
      mysqldb:
        condition: service_healthy
    entrypoint: ["sh", "-c", "docker/php-fpm/startup-script.sh"]
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '443:443'
    networks:
      - bridge
    volumes:
      - './docker/nginx/config:/etc/nginx/conf.d/'
      - '.:/var/www/html'
    depends_on:
      - blog

networks:
  bridge:
    driver: bridge

volumes:
  mysqldb:
    driver: local
